CREATE TABLE IF NOT EXISTS meta_unidade (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  ano_mes CHAR(7) NOT NULL,
  meta_gmv NUMERIC(15,2) NOT NULL DEFAULT 0,
  m1_teto NUMERIC(15,2) NOT NULL DEFAULT 600000,
  m1_pct  NUMERIC(5,2)  NOT NULL DEFAULT 0.25,
  m2_teto NUMERIC(15,2) NOT NULL DEFAULT 1200000,
  m2_pct  NUMERIC(5,2)  NOT NULL DEFAULT 0.35,
  m3_teto NUMERIC(15,2) NOT NULL DEFAULT 2000000,
  m3_pct  NUMERIC(5,2)  NOT NULL DEFAULT 0.65,
  m4_pct  NUMERIC(5,2)  NOT NULL DEFAULT 1.00,
  criado_em    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (tenant_id, ano_mes)
);
CREATE INDEX IF NOT EXISTS idx_meta_unidade_tenant_mes ON meta_unidade(tenant_id, ano_mes);
